
# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
sudo: required
language: c
addons:
  apt:
    packages: [ libgnutls28-dev, libjansson-dev, check, libsubunit-dev, cppcheck, pkg-config, doxygen ]
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)

script:
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_RHONABWY_TESTING=on -DWITH_JOURNALD=off ..
  - make test || (cat Testing/Temporary/LastTest.log && false)
  - make package
  - make install
