
# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
language: c
os: linux
dist: bionic
addons:
  apt:
    packages: [ libgnutls28-dev, libjansson-dev, libcurl4-gnutls-dev, libmicrohttpd-dev, libsystemd-dev, check, libsubunit-dev, cppcheck, pkg-config, doxygen ]
jobs:
  include:
    - env: LABEL=gcc
      compiler: gcc
    - env: LABEL=clang
      compiler: clang
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .

script:
  - mkdir build && cd build
  - cmake -DBUILD_RHONABWY_TESTING=on ..
  - make test || (cat Testing/Temporary/LastTest.log && false)
  - make package
  - sudo make install
