name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck libsystemd-dev libgnutls28-dev libjansson-dev libcurl4-gnutls-dev libmicrohttpd-dev valgrind doxygen gnutls-bin
    - name: cppcheck
      run: cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .
    - name: build
      run: |
        # prepare build folders
        mkdir build
        # build ulfius, run tests, build package
        cd build
        cmake -DBUILD_RHONABWY_TESTING=on -DBUILD_RHONABWY_DOCUMENTATION=on -DWITH_ULFIUS=OFF ..
        make
        rm -rf *
        cmake -DBUILD_RHONABWY_TESTING=on -DBUILD_RHONABWY_DOCUMENTATION=on ..
        ../test/cert/create-cert.sh || (cat ../test/cert/certtool.log && false)
        ln -s ../test/cert/ .
        ln -s ../test/cookbook-master .
        ln -s ../test/ .
        make test || (cat Testing/Temporary/LastTest.log && false)
        make package
        make doc
        sudo make install
        sudo ldconfig
        # test rnbyc
        cd ../tools/rnbyc/
        make test
